name: CoP

#on: [push]

env:
  BASE: https://hugeota.d.miui.com/20.8.7/miui_CRUX_20.8.7_19e7fe6b23_10.0.zip
  DEVICE: ginkgo
  DYNAMIC: false
  MODNAME: miui
  MIUIVER: 20.8.7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup env
         run: |
              mkdir work
              cd work
              sudo apt install wget aria2 python brotli expect 
       
       - name: Dynamic porting
         if: env.DYNAMIC == 'true'
         run:  |
               bash dynamic.sh
               cd work
               mv *.zip $MODNAME_RedmiNote9S_$MIUIVER_henlotools_10.zip
               ls

       - name: Non-Dynamic porting
         if: env.DYNAMIC == 'false'
         run: |
             bash common.sh
             cd work
             mv *.zip $MODNAME_RedmiNote9S_$MIUIVER_henlotools_10.zip

       - name: Upload Port ROM
         run: |
              cd work
              ls
              expect -c "
              spawn sftp jamieho@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"cd /home/frs/project/jamie-roms/miuiport\r\"
              set timeout -1
              send \"put *RedmiNote9S*.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              send \"exit\r\"
              interact"
              echo "Done!"
              
       - name: Done!
         run: echo bruh
