name: CoP

on: [push]

env:
  BASE: https://hugeota.d.miui.com/20.8.7/miui_CRUX_20.8.7_19e7fe6b23_10.0.zip
  DEVICE: ginkgo
  MODNAME: miui
  MIUIVER: 20.8.7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Setup env.
         run: |
              mkdir work
              cd work
              sudo apt install wget aria2 python brotli 
       
       - name: Download Pre-Ported FW from Phoenix
         if: env.BASE== "phoenix"
         run:  |
               aria2c http://tdrive.manofuranium.workers.dev/xiaomi.eu_multi_RedmiNote9Pro_RedmiNote9S_20.7.30_v12-10.zip
               unzip *.zip -d work
               rm -f *,zip
               cd work
               rm -rf system.new.dat.br system.patch.dat system.transfer.list product.new.dat.br product.transfer.list product.patch.dat
               
       - name: Download Pre-Ported FW from ginkgo
         if: env.BASE== "ginkgo"
         run: |
             aria2c http://tdrive.manofuranium.workers.dev/ROS-MIUI_RedmiNote9S_20.7.29_v12-10.zip
             unzip *.zip -d work
             rm -f *.zip
             cd work
             rm -f system.new.dat.br system.patch.dat system.transfer.list
             
       - name: Download port ROM
         if: env.DEVICE== "phoenix"
         run: |
              aria2c $BASE
              unzip *.zip system.new.dat.br system.transfer.list system.patch.dat product.new.dat.br product.transfer.list product.patch.dat -d work -qq
              rm -f *.zip
              cd work
              zip -r $ZIPNAME_RedmiNote9S_$MIUIVER_henlotools-10.zip
            
       - name: Download port ROM
         if: env.DEVICE== "ginkgo"
         run: |
              aria2c $BASE
              unzip *.zip system.new.dat.br system.transfer.list system.patch.dat -d work -qq
              rm -f *.zip
              cd work
              zip -r $ZIPNAME_RedmiNote9S_$MIUIVER_henlotools-10.zip .
              
       - name: Upload Port ROM
         run: |
              cd work
              spawn sftp jamieho@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"cd /home/frs/project/jamie-roms/miuiport\r\"
              set timeout -1
              send \"put $ZIPNAME_RedmiNote9S_$MIUIVER_henlotools-10.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              send \"exit\r\"
              echo "Done!"
              
       - name: Done!
         run: echo bruh
